### ISSUE TITLE
Splitting a file into 50k parts generates larger files

### ISSUE THREAD

**Issue by adnseek** [tolik505/split-csv#7] opened 2023-01-09 10:59 UTC
hi Tolik505,

i am using your great split-csv lib for golang

but if i try to split a big csv into 50k files, lot of bigger files land in the destination folder (see screenshot)

Do you have an idea why ? 

my setup looks like this

splitDir = "/tmp/split"
	splitter = split_csv.New()
	splitter.Separator = ";" // "," is by default
	splitter.FileChunkSize = 50000
	splitter.WithHeader = false

path := "/tmp/split/feed__" + fileID + "__.csv"
	csvfile, err := os.Create(path)
	defer csvfile.Close()

	io.Copy(csvfile, reader)

	splitter.Split(path, splitDir)

Adrian
(i attached a screenshot in the comment)

**Comment by adnseek** [comment] 2023-01-09 11:00
![forge@snapshot-90054306-ubuntu-16gb-fsn1-1: :tmp:split 2023-01-09 11-55-18](https://user-images.githubusercontent.com/120753123/211293276-1862425d-1023-449c-a588-d54d40f1df7c.png)

**Comment by tolik505** [comment] 2023-01-09 18:17
Hi Adrian. Thanks for reporting!
What version are you using?

**Comment by adnseek** [comment] 2023-01-09 19:22
"github.com/tolik505/split-csv"

**Comment by tolik505** [comment] 2023-01-11 09:34
There are 3 versions of the package https://github.com/tolik505/split-csv/releases
You can check the version in go.mod of your project.

**Comment by adnseek** [comment] 2023-01-11 21:55
Its version 1.2.0

**Comment by tolik505** [comment] 2023-01-11 22:40
Ok, got it. I'll investigate the case.

**Comment by tolik505** [comment] 2023-01-15 08:57
Hi Adrian. While testing your case I found an opposite bug when some files are significantly smaller than FileChunkSize. Could you share a file which produces the issue you mentioned?

**Comment by tolik505** [comment] 2023-01-29 18:56
The bug with smaller file chunks is fixed now.
But I couldn't reproduce the original reported bug.

**Comment by tolik505** [comment] 2023-02-17 11:53
Since I couldn't reproduce the reported bug I'm closing the issue.

**Closed as completed by tolik505** 2023-02-17 11:53 UTC
Labels: bug
